"use strict";

module.exports = {
    TILE_SIZE: 48,
    PLAYER_HITBOX_GAP: 8,
    BULLET_SPEED_UNITS_PER_MS: 0.80,
    BULLET_MAX_RANGE: 3000,
    BULLET_DAMAGE: 5,
    BULLET_FLARE_SPEED: 0.10,
    DAMAGE_ROCKET: 8,
    DAMAGE_FLARE: 5,
    MAX_HEALTH: 40,
    DAMAGE_MINE: 19,
    DAMAGE_BOMB: 25,
    BOMB_TIMER_MS: 5000,
    BOMB_ITEM_TILE_RADIUS: 2,
    BOMB_EXPLOSION_TILE_RADIUS: 3,
    TIMER_CLOAK: 5000,
    TIMER_DFG: 5000,
    COMMAND_CENTER_WIDTH_TILES: 3,
    COMMAND_CENTER_HEIGHT_TILES: 2,
    ORBABLE_SIZE: 21,
};
