"use strict";

module.exports = {
    TILE_SIZE: 48,
    PLAYER_HITBOX_GAP: 8,
    BULLET_SPEED_UNITS_PER_MS: 0.80,
    BULLET_MAX_RANGE: 3000,
    BULLET_DAMAGE: 5,
    MAX_HEALTH: 40,
    DAMAGE_MINE: 19,
    DAMAGE_BOMB: 25,
    BOMB_TIMER_MS: 5000,
    BOMB_ITEM_TILE_RADIUS: 2,
    BOMB_EXPLOSION_TILE_RADIUS: 3
};
