"use strict";

const {
  TILE_SIZE,
  MAX_HEALTH,
  PLAYER_HITBOX_GAP,
  COMMAND_CENTER_WIDTH_TILES,
  COMMAND_CENTER_HEIGHT_TILES
} = require("../server/src/gameplay/constants");

const MAP_SIZE_TILES = 512;
const MAP_PIXEL_SIZE = MAP_SIZE_TILES * TILE_SIZE;
const DEFAULT_SERVER_URL = process.env.BATTLECITY_SERVER || "http://localhost:8021";

const BLOCKING_TILE_VALUES = new Set([1, 2, 3]);

const DEFAULT_STEP_PX = 28;
const STEP_PER_TICK_PX = Number.isFinite(Number(process.env.BOT_STEP_PX))
  ? Number(process.env.BOT_STEP_PX)
  : DEFAULT_STEP_PX;
const TICK_INTERVAL_MS = Number(process.env.BOT_TICK_MS) || 120;

const TARGET_REACH_RADIUS_PX = Math.floor(TILE_SIZE * 0.40);
const MIN_TRAVEL_TILES = 3;
const MIN_TRAVEL_PX = MIN_TRAVEL_TILES * TILE_SIZE;

const PATROL_MIN_TILES = 6;
const PATROL_MAX_TILES = 14;
const LEASH_MAX_TILES = 18;

const OB_PAD_PX = Math.max(PLAYER_HITBOX_GAP, Math.ceil(TILE_SIZE * 0.15));
const LOS_STEP_PX = Math.max(6, Math.floor(TILE_SIZE / 6));

const RECALC_DEBOUNCE_MS = 80;
const STALL_TICKS = 6;

const DEFAULT_BUILDING_TILES = 4;

const PLAYER_RECT_SIZE = TILE_SIZE - (PLAYER_HITBOX_GAP * 2);

const NAV_DEFAULTS = {
  stepPerTickPx: STEP_PER_TICK_PX,
  targetReachRadiusPx: TARGET_REACH_RADIUS_PX,
  minTravelPx: MIN_TRAVEL_PX,
  patrolMinTiles: PATROL_MIN_TILES,
  patrolMaxTiles: PATROL_MAX_TILES,
  leashMaxTiles: LEASH_MAX_TILES,
  replanDebounceMs: RECALC_DEBOUNCE_MS,
  stallTicks: STALL_TICKS
};

module.exports = {
  TILE_SIZE,
  MAX_HEALTH,
  PLAYER_HITBOX_GAP,
  COMMAND_CENTER_WIDTH_TILES,
  COMMAND_CENTER_HEIGHT_TILES,
  MAP_SIZE_TILES,
  MAP_PIXEL_SIZE,
  DEFAULT_SERVER_URL,
  BLOCKING_TILE_VALUES,
  DEFAULT_STEP_PX,
  STEP_PER_TICK_PX,
  TICK_INTERVAL_MS,
  TARGET_REACH_RADIUS_PX,
  MIN_TRAVEL_TILES,
  MIN_TRAVEL_PX,
  PATROL_MIN_TILES,
  PATROL_MAX_TILES,
  LEASH_MAX_TILES,
  OB_PAD_PX,
  LOS_STEP_PX,
  RECALC_DEBOUNCE_MS,
  STALL_TICKS,
  DEFAULT_BUILDING_TILES,
  PLAYER_RECT_SIZE,
  NAV_DEFAULTS
};
